name = "S3PATH"
uuid = "94d20e9e-c806-4d6f-8ac0-01928ab83293"
version = "0.2.2"

[deps]
AWS = "fbe9abb3-538b-5e4e-ba9e-bc94f4f92ebc"
Retry = "20febd7b-183b-5ae2-ac4a-720e7ce64774"

[extras]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Conda", "Pkg", "Test", "TestItemRunner"]
